// Auto-generated type for design property keys
// This should match the keys used in DESIGN_PROPERTY_REGISTRY array
export type DesignPropertyKey =
  | "flexLayout"
  | "borderRadius"
  | "opacity"
  | "overflow"
  | "visibility"
  | "fontFamily"
  | "fontSize"
  | "fontWeight"
  | "textColor"
  | "letterSpacing"
  | "padding"
  | "margin"
  | "width"
  | "height"
  | "minWidth"
  | "maxWidth"
  | "minHeight"
  | "maxHeight"
  | "aspectRatio"
  | "position"
  | "zIndex"
  | "backgroundColor"
  | "backgroundImage"
  | "backgroundSize"
  | "backgroundPosition"
  | "backgroundRepeat"
  | "backgroundOrigin"
  | "backgroundAttachment"
  | "backgroundClip";
