export * from "./matchers/isFontSizeClass";
export * from "./matchers/isTextAlignClass";
export * from "./matchers/isTextColorClass";
export * from "./rules";
export * from "./services/classifyTextClass";
export * from "./services/getTextClassesByProperty";
export * from "./utils/matchesFontSize";
export * from "./utils/matchesTextAlign";
export * from "./utils/matchesTextColor";
