export const EDITOR_THEME = {
  light: {
    colors: {
      surface1: "#ffffff",
      surface2: "#EFEFEF",
      surface3: "#F3F3F3",
      clickable: "#808080",
      base: "#323232",
      disabled: "#C5C5C5",
      hover: "#4D4D4D",
      accent: "#6366f1",
      error: "#ff453a",
      errorSurface: "#ffeceb",
    },
    syntax: {
      plain: "#151515",
      comment: {
        color: "#999",
        fontStyle: "italic" as const,
      },
      keyword: "#6366f1",
      tag: "#d28cf6",
      punctuation: "#3B3B3B",
      definition: "#282960",
      property: "#6366f1",
      static: "#FF453A",
      string: "#bf5af2",
    },
    font: {
      body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
      mono: '"Fira Mono", "DejaVu Sans Mono", Menlo, Consolas, "Liberation Mono", Monaco, "Lucida Console", monospace',
      size: "12px",
      lineHeight: "18px",
    },
  },
  dark: {
    colors: {
      surface1: "#151515",
      surface2: "#252525",
      surface3: "#2F2F2F",
      clickable: "#999999",
      base: "#808080",
      disabled: "#4D4D4D",
      hover: "#C5C5C5",
      accent: "#6366f1",
      error: "#ff453a",
      errorSurface: "#ffeceb",
    },
    syntax: {
      plain: "#FFFFFF",
      comment: {
        color: "#757575",
        fontStyle: "italic" as const,
      },
      keyword: "#6366f1",
      tag: "#d28cf6",
      punctuation: "#ffffff",
      definition: "#c1c2f9",
      property: "#6366f1",
      static: "#FF453A",
      string: "#bf5af2",
    },
    font: {
      body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
      mono: '"Fira Mono", "DejaVu Sans Mono", Menlo, Consolas, "Liberation Mono", Monaco, "Lucida Console", monospace',
      size: "12px",
      lineHeight: "18px",
    },
  },
};
