export const STANDARD_FONTS = ["sans", "serif", "mono"] as const;

export const GOOGLE_FONTS = [
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Oswald",
  "Raleway",
  "Poppins",
  "Merriweather",
  "Nunito",
  "Playfair Display",
  "Ubuntu",
  "Mukta",
  "Rubik",
  "Quicksand",
  "Work Sans",
  "Karla",
  "Inter",
  "Bebas Neue",
  "Fira Sans",
  "Noto Sans",
  "PT Sans",
  "Barlow",
  "DM Sans",
  "Manrope",
  "Space Grotesk",
  "Outfit",
  "Plus Jakarta Sans",
  "Source Sans Pro",
  "Crimson Text",
  "Libre Baskerville",
  "Cormorant Garamond",
  "Lora",
  "PT Serif",
  "Libre Franklin",
  "Bitter",
  "EB Garamond",
  "Arvo",
  "Josefin Sans",
  "Inconsolata",
  "JetBrains Mono",
  "Source Code Pro",
  "Fira Code",
  "IBM Plex Mono",
  "Roboto Mono",
  "Space Mono",
  "Courier Prime",
] as const;

export type StandardFont = (typeof STANDARD_FONTS)[number];
export type GoogleFont = (typeof GOOGLE_FONTS)[number];

