export type { FormattedParam, Properties } from "@project/ast-parser";
export { useFileReferenceCode } from "./hooks/useFileReferenceCode";
export { useLayerTree } from "./hooks/useLayerTree";
export { useSelectedNodeData } from "./hooks/useSelectedNodeData";
export { useSelectedNodeTitle } from "./hooks/useSelectedNodeTitle";
export {
  addFile,
  updateFileStore,
  getAllFiles,
  getFile,
  getFileAST,
  getFileCode,
  getFileClassSuggestions,
  setFileClassSuggestions,
  removeFileClassSuggestions,
  clearFileClassSuggestions,
  getFileExportType,
  getFileHistory,
  getFileLayerTree,
  getFileParams,
  getFileProperties,
  getLastChangedSandpackFile,
  getSandpackFiles,
  removeFile,
  removeSandpackFile,
  updateAllFileCode,
  updateFileAST,
  updateFileCode,
  updateFileContent,
  updateFileExportType,
  updateFileHistory,
  updateFileLayerTree,
  updateFileName,
  updateFileParams,
  updateFilePath,
  updateFileProperties,
  updateFileViewportWidth,
  updateSandpackFile,
  updateSandpackFiles,
  useFileManagerStore,
  useLastChangedSandpackFile,
  useStoreFile,
  useStoreFiles,
} from "./stores/fileManagerStore";
export { getFilesMap } from "./utils/getFilesMap";
